import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="font-lg text-red sm:text-yellow md:text-blue lg:text-green xl:text-pink">
          Text
        </div>
      </main>
    </>
  );
}
